---
openapi: 3.0.1
info:
  title: Commenda Public APIs
  description:
    APIs for Commenda entity management, partner incorporation, indirect tax,
    compliance, and corporate operations.
  license:
    name: NONE
    url: NONE
  version: 1.0.0
servers:
  - url: https://api.prod.commenda.io/api/v1
    description: Commenda platform APIs, including Partner Incorporation and Commenda OS.
  - url: https://transaction-tax.api.in.commenda.io/api/v1
    description: Global Indirect Tax API.
security:
  - bearerAuth: []

components:
  $ref: "./components/components.yaml#/components"

paths:
  $ref: "./paths/paths.yaml"
